### ISSUE TITLE
Duplicate elimination disabled?

### ISSUE THREAD

**Issue by mirddes** [thiagodesacosta/HPIZ-Archiver#2]
![image](https://user-images.githubusercontent.com/13982888/180678699-cc950bfd-078a-4ff5-9f73-d57bfc6d3bec.png)

i deliberately duplicated several directories to improve accessibility of the tileset compliation (cross referencing transitions)

unfortunately the resulting archive expanded by the appropriate amount instead of the size staying static due to deduplication.

i didn't think much of it this morning until i checked the filesize and upon reopening hpiz-archiver i find the duplicate rules button greyed out :(

please advise, this software is amazing (and i love the resizing window)

**Comment by THGSCST** [comment]
The duplicate function is for dealing with files of the same **name**, which came from different folders and need to be merged into a single file. Your files all have different names and do not enter the rule. What you want is a new function, something that finds the **hash** of each file.

I can implement it, but I'll need to think about how to include it in the rule logic. In the meantime, you can use any tool that calculates the hash of each file in a folder. Any algorithm can be used, like MD5 or SHA and others.

https://github.com/THGSCST/HPIZ-Archiver/projects/1#column-9130413

**Comment by mirddes** [comment]
I figured the directories I duplicated should all contain identically named
files.
Comparing all filenames before hashing could be optimal
performance/function.
Tileset subfolder/tileset file.xyz
Tileset subfolder (1)/tileset file.xyz
Tileset subfolder (2)/tileset file.xyz
Tileset subfolder (3)/tileset file.xyz

**Comment by THGSCST** [comment]
I have released a new beta version that has these features. May contain bugs, not fully tested. https://github.com/THGSCST/HPIZ-Archiver/releases/tag/r1.3b
