### ISSUE TITLE
crashes when trying to open the HPI in this zip.

### ISSUE THREAD

**Issue by mirddes** [thiagodesacosta/HPIZ-Archiver#5]
[U_EG2_Transitons.zip](https://github.com/user-attachments/files/17165595/U_EG2_Transitons.zip)

this one seems to crash it :(

**Comment by mirddes** [comment]
whatever it did to the hpi caused mappy to refuse to launch until the file was deleted and replaced with a fresh copy. im gonna reboot my pc and see if that magics everything perfect

**Comment by THGSCST** [comment]
I was able to successfully open, extract, and repack all the contents of the attached HPI file without any issues. It’s possible that on your computer, the file may have been in use by another program, which could have caused the problem.

In the next version of the HPIZ-Archiver, detailed error messages will be included for all operations to help troubleshoot these kinds of situations.
